#system parameters
N_uc: 6 #number of unit cells
S: 0.5 #spin length
Js: #exchange coupling constants
  - 1.0
  - -0.3
  - 0.0
  - 0.0
include_cubic: false #whether to include cubic spin interaction S^z S^+ S^z
K: #cubic interaction strength (real and imaginary parts)
  - 0.0
  - 0.0
#external magnetic field parameters
h_theta: 0.0 #magnetic field angle between [111] and [11-2] directions (degrees)
h_sweep_args:
  - 0.5
  - 4.5
N_h: 2
delta_12: #quadratic zeeman coupling constants
  - 0.0
  - 0.0
#disorder (random transverse field) parameters
disorder_strength: 0.0
disorder_seed: 123456
#monte carlo simulation parameters
sim_anneal:
  job:
    time: "1:00:00"
    mem_per_cpu: "1000M"
    job_name: "theta=90.0"
  file_prefix: "test_simanneal_h"
  results_dir: "../sim_anneal_out" #temporary storage
  save_dir: "../theta_sweep" #final storage
  mc_params:
    N_therm: 1000000
    overrelax_rate: 10
    N_det: 0
  T_args: #temperature schedule
    - 0.002
    - 3.0
  #save configurations at low T for use as initial conditions
  save_configs: false
  T_save_args:
    - 0.001
    - 0.25
  N_save: 48
  save_configs_prefix: "../pt_collect/save_config/Jpm=0_Jpmpm+_h"
parallel_temper:
  job:
    time: "1:00:00"
    mem_per_cpu: "1G"
    job_name: "pt_test"
  mc_params:
    N_therm: 200000
    overrelax_rate: 10
    N_meas: 600000
    probe_rate: 200
    replica_exchange_rate: 50
    optimize_temperature_rate: 20000000
  load_configs: false #load saved temperatures and configurations
  load_configs_prefix: "../pt_collect/save_config/Jpm+_Jpmpm-_h"
  T_args: #otherwise use the following temperature range with NTs ranks
    - 0.001
    - 1.0
  N_Ts: 192
  file_prefix: "test_ising_Jpm=-0.3_h"
  results_dir: "../pt_out" #temporary storage
  save_dir: "../pt_collect/final" #final storage
